name: flutterfire
description: Flutter Firebase Example.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5345
  modal_progress_hud: ^0.1.3

  injectable: ^1.0.2
  get_it: ^4.0.4
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  validators: ^2.0.1
  ulid: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  injectable_generator: ^1.0.3

flutter:
  uses-material-design: true
